# 開発環境用

version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: ddd-nginx
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8801:80
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/logrotate.d/nginx:/etc/logrotate.d/nginx
      - ./:/var/www/html
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
    container_name: ddd-php
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini
      - ./docker/php/log:/var/log
    depends_on:
      - db
  db:
    image: mariadb
    container_name: ddd-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
      TZ: Asia/Tokyo
    volumes:
      - database-volume:/var/lib/mysql
      - ./docker/db/config:/etc/mysql/conf.d
      - ./docker/db/init.d:/docker-entrypoint-initdb.d
    ports:
      - 13306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ddd-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db
    ports:
      - 8802:80

volumes:
  database-volume:
